version: "3"

services:
  app:
    container_name: node_app
    restart: always
    build: .
    ports:
      - '5001:5001'
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: chandan
      MYSQL_PASSWORD: iamchiranjeeb
      MYSQL_ROOT_PASSWORD: iamchiranjeeb
